### ISSUE TITLE
Flaky behavior on deployed apps - loader runs forever, cannot access posts directly via URL

### ISSUE THREAD

**Issue by ViolanteCodes** [ButterCMS/gridsome-starter-buttercms#6]
See video: [link](https://share.getcloudapp.com/qGuZoOK0)

First error from video:

Uncaught (in promise) DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (https://gridsome-starter-buttercms-for-video.vercel.app/assets/js/app.0d2b0a29.js:7:47261)
    at v (https://gridsome-starter-buttercms-for-video.vercel.app/assets/js/app.0d2b0a29.js:7:60650)
    at p (https://gridsome-starter-buttercms-for-video.vercel.app/assets/js/app.0d2b0a29.js:7:60281)
    at h (https://gridsome-starter-buttercms-for-video.vercel.app/assets/js/app.0d2b0a29.js:7:60724)
    at A (https://gridsome-starter-buttercms-for-video.vercel.app/assets/js/app.0d2b0a29.js:7:64062)
    at A (https://gridsome-starter-buttercms-for-video.vercel.app/assets/js/app.0d2b0a29.js:7:63997)
    at A (https://gridsome-starter-buttercms-for-video.vercel.app/assets/js/app.0d2b0a29.js:7:63997)
    at a.__patch__ (https://gridsome-starter-buttercms-for-video.vercel.app/assets/js/app.0d2b0a29.js:7:64462)
    at Kw5r.t._update (https://gridsome-starter-buttercms-for-video.vercel.app/assets/js/app.0d2b0a29.js:7:40754)
    at a.r (https://gridsome-starter-buttercms-for-video.vercel.app/assets/js/app.0d2b0a29.js:7:71793)
app.0d2b0a29.js:7 TypeError: Cannot read properties of undefined (reading '_isDestroyed')
    at destroy (app.0d2b0a29.js:7:28144)
    at w (app.0d2b0a29.js:7:61432)
    at w (app.0d2b0a29.js:7:61531)
    at w (app.0d2b0a29.js:7:61531)
    at a.__patch__ (app.0d2b0a29.js:7:64945)
    at Kw5r.t.$destroy (app.0d2b0a29.js:7:41269)
    at destroy (app.0d2b0a29.js:7:28344)
    at w (app.0d2b0a29.js:7:61432)
    at a.__patch__ (app.0d2b0a29.js:7:64945)
    at Kw5r.t.$destroy (app.0d2b0a29.js:7:41269)
We @ app.0d2b0a29.js:7
DevTools failed to load source map: Could not load content for chrome-extension://ojnikmlgjpfiogeijjkpeakbedjhjcch/toggle_icon.js.map: System error: net::ERR_BLOCKED_BY_CLIENT

Second error:

app.0d2b0a29.js:7 Uncaught (in promise) DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (https://gridsome-starter-buttercms-for-video.vercel.app/assets/js/app.0d2b0a29.js:7:47261)
    at v (https://gridsome-starter-buttercms-for-video.vercel.app/assets/js/app.0d2b0a29.js:7:60650)
    at p (https://gridsome-starter-buttercms-for-video.vercel.app/assets/js/app.0d2b0a29.js:7:60281)
    at h (https://gridsome-starter-buttercms-for-video.vercel.app/assets/js/app.0d2b0a29.js:7:60724)
    at A (https://gridsome-starter-buttercms-for-video.vercel.app/assets/js/app.0d2b0a29.js:7:64062)
    at A (https://gridsome-starter-buttercms-for-video.vercel.app/assets/js/app.0d2b0a29.js:7:63997)
    at A (https://gridsome-starter-buttercms-for-video.vercel.app/assets/js/app.0d2b0a29.js:7:63997)
    at a.__patch__ (https://gridsome-starter-buttercms-for-video.vercel.app/assets/js/app.0d2b0a29.js:7:64462)
    at Kw5r.t._update (https://gridsome-starter-buttercms-for-video.vercel.app/assets/js/app.0d2b0a29.js:7:40754)
    at a.r (https://gridsome-starter-buttercms-for-video.vercel.app/assets/js/app.0d2b0a29.js:7:71793)
appendChild @ app.0d2b0a29.js:7
v @ app.0d2b0a29.js:7
p @ app.0d2b0a29.js:7
h @ app.0d2b0a29.js:7
A @ app.0d2b0a29.js:7
A @ app.0d2b0a29.js:7
A @ app.0d2b0a29.js:7
(anonymous) @ app.0d2b0a29.js:7
Kw5r.t._update @ app.0d2b0a29.js:7
r @ app.0d2b0a29.js:7
t.get @ app.0d2b0a29.js:7
t @ app.0d2b0a29.js:7
t @ app.0d2b0a29.js:7
Kw5r.ur.$mount @ app.0d2b0a29.js:7
init @ app.0d2b0a29.js:7
A @ app.0d2b0a29.js:7
A @ app.0d2b0a29.js:7
A @ app.0d2b0a29.js:7
(anonymous) @ app.0d2b0a29.js:7
Kw5r.t._update @ app.0d2b0a29.js:7
r @ app.0d2b0a29.js:7
t.get @ app.0d2b0a29.js:7
t @ app.0d2b0a29.js:7
t @ app.0d2b0a29.js:7
Kw5r.ur.$mount @ app.0d2b0a29.js:7
init @ app.0d2b0a29.js:7
A @ app.0d2b0a29.js:7
(anonymous) @ app.0d2b0a29.js:7
Kw5r.t._update @ app.0d2b0a29.js:7
r @ app.0d2b0a29.js:7
t.get @ app.0d2b0a29.js:7
t @ app.0d2b0a29.js:7
t @ app.0d2b0a29.js:7
Kw5r.ur.$mount @ app.0d2b0a29.js:7
init @ app.0d2b0a29.js:7
A @ app.0d2b0a29.js:7
(anonymous) @ app.0d2b0a29.js:7
Kw5r.t._update @ app.0d2b0a29.js:7
r @ app.0d2b0a29.js:7
t.get @ app.0d2b0a29.js:7
t @ app.0d2b0a29.js:7
t @ app.0d2b0a29.js:7
Kw5r.ur.$mount @ app.0d2b0a29.js:7
init @ app.0d2b0a29.js:7
n @ app.0d2b0a29.js:7
A @ app.0d2b0a29.js:7
(anonymous) @ app.0d2b0a29.js:7
Kw5r.t._update @ app.0d2b0a29.js:7
r @ app.0d2b0a29.js:7
t.get @ app.0d2b0a29.js:7
t @ app.0d2b0a29.js:7
t @ app.0d2b0a29.js:7
Kw5r.ur.$mount @ app.0d2b0a29.js:7
init @ app.0d2b0a29.js:7
A @ app.0d2b0a29.js:7
(anonymous) @ app.0d2b0a29.js:7
Kw5r.t._update @ app.0d2b0a29.js:7
r @ app.0d2b0a29.js:7
t.get @ app.0d2b0a29.js:7
t @ app.0d2b0a29.js:7
t @ app.0d2b0a29.js:7
Kw5r.ur.$mount @ app.0d2b0a29.js:7
(anonymous) @ app.0d2b0a29.js:20
(anonymous) @ app.0d2b0a29.js:20
(anonymous) @ app.0d2b0a29.js:20
(anonymous) @ app.0d2b0a29.js:20
r @ app.0d2b0a29.js:20
r @ app.0d2b0a29.js:20
Ae @ app.0d2b0a29.js:20
(anonymous) @ app.0d2b0a29.js:20
r @ app.0d2b0a29.js:20
(anonymous) @ app.0d2b0a29.js:20
(anonymous) @ app.0d2b0a29.js:20
(anonymous) @ app.0d2b0a29.js:20
(anonymous) @ app.0d2b0a29.js:20
Promise.then (async)
(anonymous) @ app.0d2b0a29.js:20
(anonymous) @ app.0d2b0a29.js:20
(anonymous) @ app.0d2b0a29.js:20
Te @ app.0d2b0a29.js:20
(anonymous) @ app.0d2b0a29.js:20
h @ app.0d2b0a29.js:20
r @ app.0d2b0a29.js:20
r @ app.0d2b0a29.js:20
(anonymous) @ app.0d2b0a29.js:20
(anonymous) @ app.0d2b0a29.js:20
e.a @ app.0d2b0a29.js:20
h @ app.0d2b0a29.js:20
r @ app.0d2b0a29.js:20
Ae @ app.0d2b0a29.js:20
Nvoc.$e.confirmTransition @ app.0d2b0a29.js:20
Nvoc.$e.transitionTo @ app.0d2b0a29.js:20
Nvoc.He.init @ app.0d2b0a29.js:20
beforeCreate @ app.0d2b0a29.js:20
Ue @ app.0d2b0a29.js:7
hn @ app.0d2b0a29.js:7
Kw5r.t._init @ app.0d2b0a29.js:7
ur @ app.0d2b0a29.js:7
Nvoc @ app.0d2b0a29.js:20
a @ app.0d2b0a29.js:1
0 @ app.0d2b0a29.js:1
a @ app.0d2b0a29.js:1
n @ app.0d2b0a29.js:1
(anonymous) @ app.0d2b0a29.js:1
(anonymous) @ app.0d2b0a29.js:1

**Comment by prokopsimek** [comment]
It seems that there is still an open issue as of September 9, 2019 that relates to this issue.
https://github.com/gridsome/gridsome/issues/650

I've spent about 2 hours debugging and trying to figure it out and I don't know how to fix it.
